# Generated by Django 3.1.2 on 2020-10-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='mision',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='vision',
            field=models.TextField(max_length=500),
        ),
    ]
