# Generated by Django 3.1.2 on 2020-10-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_slider_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='nombre',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
