# Generated by Django 3.1.2 on 2020-10-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_gallery_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='')),
                ('descripcion', models.TextField(max_length=200, null=True)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
