# Generated by Django 3.1.2 on 2020-10-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201027_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
